services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq-server
    networks:
      - rabbot-message-redriver
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    volumes:
     - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
networks:
  rabbot-message-redriver: